CREATE TABLE SK_USER (USER_NAME VARCHAR2,USER_EMAIL VARCHAR2,USER_MOBILE VARCHAR2,AGE NUMBER(3),ADDRESS VARCHAR2);
/
CREATE TABLE SK_ITEM (ITEM_ID VARCHAR2 PRIMARY KEY,ITEM_NAME VARCHAR2,ITEM_DESCRIPTION VARCHAR2,PRICE NUMBER,AVAILABLE_QUANTITY NUMBER,ITEM_IMAGE_ID VARCHAR2,CATEGORY VARCHAR2 );
/
CREATE TABLE SK_ADDRESS (ADDRESS_ID VARCHAR2 PRIMARY KEY,STREET_LINE1 VARCHAR2,STREET_LINE2 VARCHAR2,CITY VARCHAR2,STATE VARCHAR2,COUNTRY VARCHAR2,PIN VARCHAR2,ADDRESS_TYPE VARCHAR2,ISDEFAULT CHAR(1));
/
CREATE TABLE SK_ORDER (ORDER_ID VARCHAR2 PRIMARY KEY,CREATED_DATE VARCHAR2,DELIVERY_DATE VARCHAR2,ITEMS VARCHAR2,USER_ID VARCHAR2,ADDRESS_ID VARCHAR2);
/
CREATE TABLE SK_ORDERLINE (ORDERLINE_ID VARCHAR2 PRIMARY KEY,ITEM_ID VARCHAR2,ITEM_NAME VARCHAR2,ITEM_DESCRIPTION VARCHAR2,PRICE NUMBER,ORDERED_QUANTITY NUMBER);
/
stop